class SyntaxError extends globalThis.SyntaxError {
    /**
   * Constructs the human-readable message from the machine representation.
   *
   * @param expected Array of expected items, generated by the parser
   * @param found Any text that will appear as found in the input instead of
   *   expected
   */
    static buildMessage(expected: Expectation[], found?: string | null | undefined): string;
    readonly expected: Expectation[];
    readonly found: string | null | undefined;
    readonly location: LocationRange;
    readonly name: string;
    constructor(
    message: string,
    expected: Expectation[],
    found: string | null,
    location: LocationRange,
  );

    /**
   * With good sources, generates a feature-rich error message pointing to the
   * error in the input.
   * @param sources List of {source, text} objects that map to the input.
   */
    format(sources: SourceText[]): string;
}